{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "chart.fullname" . }}-metrics
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    {{- if .Values.observability.prometheus.release }}
    release: {{ .Values.observability.prometheus.release }}
    {{- end }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.service.metricsPortName }}
      interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.serviceMonitor.path }}
{{- end }}
